# environment.yaml
name: myenv
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - click
  - pyyaml
  - nbformat
  - jupyterlab
  - seaborn
  - pandas
  - numpy
  - pip:
    - nbformat-cli
    - nbcell-check-cli
    - datavis-cli
    - pathlib-cli
    - curry-batch
    - pandas-cli
    - itertools-cli
